<?xml version="1.0" encoding="utf-8"?>
<TestRun id="eb617978-693c-4232-9b86-b3149d8b903c" name="IvanY@CP116 2021-05-17 15:44:05" runUser="TEAM\IvanY" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2021-05-17T15:44:05.8612506+03:00" queuing="2021-05-17T15:44:05.8612519+03:00" start="2021-05-17T15:44:01.1785162+03:00" finish="2021-05-17T15:44:05.8810918+03:00" />
  <TestSettings name="default" id="2e61ca36-42d4-40a6-a6ab-0c27b3e2f513">
    <Deployment runDeploymentRoot="IvanY_CP116_2021-05-17_15_44_05" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="dc30f15d-528d-4353-a78f-5440d89e6f68" testId="2c3a0854-4e79-675c-ccb0-6444089669eb" testName="GetEmployeeTest1" computerName="CP116" duration="00:00:01.2680000" startTime="2021-05-17T15:44:04.3832399+03:00" endTime="2021-05-17T15:44:05.6508976+03:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="dc30f15d-528d-4353-a78f-5440d89e6f68">
      <Output>
        <ErrorInfo>
          <Message>System.Exception : NotFound. , response was from uri http://dummy.restapiexample.com/api/v1/employee</Message>
          <StackTrace>   at AutoPractice14.Services.Extentions.IRestResponseExtention.EnsureSuccess(IRestResponse response) in c:\Users\IvanY\Work\COE\Cources\Internal\AutoPractice14\AutoPractice14.Services\Extentions\IRestResponseExtention.cs:line 28&#xD;
   at APITests.ApiTests.GetEmployeeTest1() in c:\Users\IvanY\Work\COE\Cources\Internal\AutoPractice14base\APITests\ApiTests.cs:line 16</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="GetEmployeeTest1" storage="c:\users\ivany\work\coe\cources\internal\AutoPractice14base\apitests\bin\debug\netcoreapp2.1\apitests.dll" id="2c3a0854-4e79-675c-ccb0-6444089669eb">
      <Execution id="dc30f15d-528d-4353-a78f-5440d89e6f68" />
      <TestMethod codeBase="c:\Users\IvanY\Work\COE\Cources\Internal\AutoPractice14base\APITests\bin\Debug\netcoreapp2.1\APITests.dll" adapterTypeName="executor://nunit3testexecutor/" className="APITests.ApiTests" name="GetEmployeeTest1" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="2c3a0854-4e79-675c-ccb0-6444089669eb" executionId="dc30f15d-528d-4353-a78f-5440d89e6f68" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>NUnit Adapter 3.17.0.0: Test execution started&#xD;
Running all tests in c:\Users\IvanY\Work\COE\Cources\Internal\AutoPractice14base\APITests\bin\Debug\netcoreapp2.1\APITests.dll&#xD;
   NUnit3TestExecutor discovered 1 of 1 NUnit test cases&#xD;
NUnit Adapter 3.17.0.0: Test execution complete&#xD;
</StdOut>
    </Output>
  </ResultSummary>
</TestRun>